---
title: "SPSS Syntax used"
output: html_notebook
---

DATASET ACTIVATE DataSet1.
* Generalized Estimating Equations. * Looking at the effect of Open Data, for Open Access, change variable names.

GENLIN PhD_OD (REFERENCE=FIRST) BY SvS_OD (ORDER=DESCENDING)
  /MODEL SvS_OD INTERCEPT=YES
 DISTRIBUTION=BINOMIAL LINK=LOGIT
  /CRITERIA METHOD=FISHER(1) SCALE=1 MAXITERATIONS=100 MAXSTEPHALVING=5 PCONVERGE=1E-006(ABSOLUTE) 
    SINGULAR=1E-012 ANALYSISTYPE=3(WALD) CILEVEL=95 LIKELIHOOD=FULL
  /REPEATED SUBJECT=identifier SORT=YES CORRTYPE=INDEPENDENT ADJUSTCORR=YES COVB=ROBUST 
    MAXITERATIONS=100 PCONVERGE=1e-006(ABSOLUTE) UPDATECORR=1
  /MISSING CLASSMISSING=EXCLUDE
  /PRINT CPS DESCRIPTIVES MODELINFO FIT SUMMARY SOLUTION.

DATASET ACTIVATE DataSet1.
* Generalized Estimating Equations.
GENLIN PhD_OA (REFERENCE=LAST) BY SvS_OA_dummy_2 SvS_OA_dummy_3 SvS_OA_dummy_1 (ORDER=DESCENDING)
  /MODEL SvS_OA_dummy_2 SvS_OA_dummy_3 SvS_OA_dummy_1 INTERCEPT=YES
 DISTRIBUTION=BINOMIAL LINK=LOGIT
  /CRITERIA METHOD=FISHER(1) SCALE=1 MAXITERATIONS=100 MAXSTEPHALVING=5 PCONVERGE=1E-006(ABSOLUTE) 
    SINGULAR=1E-012 ANALYSISTYPE=3(WALD) CILEVEL=95 LIKELIHOOD=FULL
  /REPEATED SUBJECT=Identifier SORT=YES CORRTYPE=INDEPENDENT ADJUSTCORR=YES COVB=ROBUST 
    MAXITERATIONS=100 PCONVERGE=1e-006(ABSOLUTE) UPDATECORR=1
  /MISSING CLASSMISSING=EXCLUDE
  /PRINT CPS DESCRIPTIVES MODELINFO FIT SUMMARY SOLUTION.

