---
title: "SPSS Syntax"
output: html_document
---
After importing the csv file from script #5 into SPSS, the PhD candidate behavior variables were recoded into numeric values so that true = 1 and false = 0. The institute was dummy coded and added to models 4, 5, and 6. 

*Open Access - Model 1
*Generalized Estimating Equations.
GENLIN oa_status_phd (REFERENCE=FIRST) BY category_oa (ORDER=DESCENDING)
  /MODEL category_oa INTERCEPT=YES
 DISTRIBUTION=BINOMIAL LINK=LOGIT
  /CRITERIA METHOD=FISHER(1) SCALE=1 MAXITERATIONS=100 MAXSTEPHALVING=5 PCONVERGE=1E-006(ABSOLUTE) 
    SINGULAR=1E-012 ANALYSISTYPE=3(WALD) CILEVEL=95 LIKELIHOOD=FULL
  /REPEATED SUBJECT=pair SORT=YES CORRTYPE=INDEPENDENT ADJUSTCORR=YES COVB=ROBUST 
    MAXITERATIONS=100 PCONVERGE=1e-006(ABSOLUTE) UPDATECORR=1
  /MISSING CLASSMISSING=EXCLUDE
  /PRINT CPS DESCRIPTIVES MODELINFO FIT SUMMARY SOLUTION.

*Open Data Automated - Model 2
*Generalized Estimating Equations.
GENLIN is_open_data_phd (REFERENCE=FIRST) BY open_data_ever (ORDER=DESCENDING)
  /MODEL open_data_ever INTERCEPT=YES
 DISTRIBUTION=BINOMIAL LINK=LOGIT
  /CRITERIA METHOD=FISHER(1) SCALE=1 MAXITERATIONS=100 MAXSTEPHALVING=5 PCONVERGE=1E-006(ABSOLUTE) 
    SINGULAR=1E-012 ANALYSISTYPE=3(WALD) CILEVEL=95 LIKELIHOOD=FULL
  /REPEATED SUBJECT=pair SORT=YES CORRTYPE=INDEPENDENT ADJUSTCORR=YES COVB=ROBUST 
    MAXITERATIONS=100 PCONVERGE=1e-006(ABSOLUTE) UPDATECORR=1
  /MISSING CLASSMISSING=EXCLUDE
  /PRINT CPS DESCRIPTIVES MODELINFO FIT SUMMARY SOLUTION.

*Open Data Manually Verified - Model 3
* Generalized Estimating Equations.
GENLIN manually_verified_open_phd (REFERENCE=FIRST) BY open_data_numbat_ever (ORDER=DESCENDING)
  /MODEL open_data_numbat_ever INTERCEPT=YES
 DISTRIBUTION=BINOMIAL LINK=LOGIT
  /CRITERIA METHOD=FISHER(1) SCALE=1 MAXITERATIONS=100 MAXSTEPHALVING=5 PCONVERGE=1E-006(ABSOLUTE)
    SINGULAR=1E-012 ANALYSISTYPE=3(WALD) CILEVEL=95 LIKELIHOOD=FULL
  /REPEATED SUBJECT=pair SORT=YES CORRTYPE=INDEPENDENT ADJUSTCORR=YES COVB=ROBUST
    MAXITERATIONS=100 PCONVERGE=1e-006(ABSOLUTE) UPDATECORR=1
  /MISSING CLASSMISSING=EXCLUDE
  /PRINT CPS DESCRIPTIVES MODELINFO FIT SUMMARY SOLUTION.

*Open Access with Institution - Model 4
*Generalized Estimating Equations.
GENLIN oa_status_phd (REFERENCE=FIRST) BY category_oa in_1 in_2 in_3 in_4 (ORDER=DESCENDING)
  /MODEL category_oa in_1 in_2 in_3 in_4 INTERCEPT=YES
 DISTRIBUTION=BINOMIAL LINK=LOGIT
  /CRITERIA METHOD=FISHER(1) SCALE=1 MAXITERATIONS=100 MAXSTEPHALVING=5 PCONVERGE=1E-006(ABSOLUTE) 
    SINGULAR=1E-012 ANALYSISTYPE=3(WALD) CILEVEL=95 LIKELIHOOD=FULL
  /REPEATED SUBJECT=pair SORT=YES CORRTYPE=INDEPENDENT ADJUSTCORR=YES COVB=ROBUST 
    MAXITERATIONS=100 PCONVERGE=1e-006(ABSOLUTE) UPDATECORR=1
  /MISSING CLASSMISSING=EXCLUDE
  /PRINT CPS DESCRIPTIVES MODELINFO FIT SUMMARY SOLUTION.

*Open Data Automated with Institution - Model 5
*Generalized Estimating Equations.
GENLIN is_open_data_phd (REFERENCE=FIRST) BY open_data_ever in_1 in_2 in_3 in_4 (ORDER=DESCENDING)
  /MODEL open_data_ever in_1 in_2 in_3 in_4 INTERCEPT=YES
 DISTRIBUTION=BINOMIAL LINK=LOGIT
  /CRITERIA METHOD=FISHER(1) SCALE=1 MAXITERATIONS=100 MAXSTEPHALVING=5 PCONVERGE=1E-006(ABSOLUTE) 
    SINGULAR=1E-012 ANALYSISTYPE=3(WALD) CILEVEL=95 LIKELIHOOD=FULL
  /REPEATED SUBJECT=pair SORT=YES CORRTYPE=INDEPENDENT ADJUSTCORR=YES COVB=ROBUST 
    MAXITERATIONS=100 PCONVERGE=1e-006(ABSOLUTE) UPDATECORR=1
  /MISSING CLASSMISSING=EXCLUDE
  /PRINT CPS DESCRIPTIVES MODELINFO FIT SUMMARY SOLUTION.

*Open Data Manually Verified with Institution - Model 6
*Generalized Estimating Equations.
GENLIN manually_verified_open_phd (REFERENCE=FIRST) BY open_data_numbat_ever in_1 in_2 in_3 in_4 (ORDER=DESCENDING)
  /MODEL open_data_numbat_ever in_1 in_2 in_3 in_4 INTERCEPT=YES
 DISTRIBUTION=BINOMIAL LINK=LOGIT
  /CRITERIA METHOD=FISHER(1) SCALE=1 MAXITERATIONS=100 MAXSTEPHALVING=5 PCONVERGE=1E-006(ABSOLUTE)
    SINGULAR=1E-012 ANALYSISTYPE=3(WALD) CILEVEL=95 LIKELIHOOD=FULL
  /REPEATED SUBJECT=pair SORT=YES CORRTYPE=INDEPENDENT ADJUSTCORR=YES COVB=ROBUST
    MAXITERATIONS=100 PCONVERGE=1e-006(ABSOLUTE) UPDATECORR=1
  /MISSING CLASSMISSING=EXCLUDE
  /PRINT CPS DESCRIPTIVES MODELINFO FIT SUMMARY SOLUTION.
